steps:
# Step to build Flask App (app1)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Flask App'
  dir: 'flask_app'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app1:latest .

# Step to build PHP App (app2)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build PHP App'
  dir: 'php-fishing-quote-api'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app2:latest .

# Push Flask App (app1) to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Flask App to Artifact Registry'
  args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app1:latest']

# Push PHP App (app2) to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push PHP App to Artifact Registry'
  args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app2:latest']
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --location=us-central1
  - --cluster=primary-gke-cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --location=us-central1
  - --cluster=primary-gke-cluster


images:
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app1:latest'
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/sharky-enterprises/app2:latest'
